FROM alpine:3.21
RUN apk add --no-cache ca-certificates tzdata \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone
WORKDIR /app
COPY mr1v1-wx ./mr1v1-wx
ENTRYPOINT ["./mr1v1-wx"]
